//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F2BMVCAngularApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public city()
        {
            this.EmployeeAddresses = new HashSet<EmployeeAddress>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public int StateID { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<EmployeeAddress> EmployeeAddresses { get; set; }
    }
}
