//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F2BMVCAngularApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
    
        public virtual EmployeeAddress EmployeeAddress { get; set; }
    }
}
