//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F2BMVCAngularApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddress
    {
        public int AddressID { get; set; }
        public Nullable<int> FlatNo { get; set; }
        public string street { get; set; }
        public string Country { get; set; }
        public Nullable<int> Pincode { get; set; }
        public int CityID { get; set; }
        public int StateID { get; set; }
    
        public virtual city city { get; set; }
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual State State { get; set; }
    }
}
